# Generated by Django 5.0.2 on 2025-08-02 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='reply',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reply',
            name='edited_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='follow_up_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='follow_up_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='follow_up_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='marked_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='marked_successful_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='marked_successful_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successful_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='requires_manual_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='success_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reddit_comment_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
